package org.openntf.xrest.xsp.model;

public enum EventType {
	VALIDATE, PRE_SAVE_DOCUMENT, POST_SAVE_DOCUMENT, PRE_LOAD_DOCUMENT, POST_LOAD_DOCUMENT, PRE_SUBMIT, POST_NEW, PRE_DELETE, POST_DELETE, ALT_DOCUMENT_UPDATE, ALT_DOCUMENT_DELETE;

}
